{
	"version": 1738123702,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-3.4.1.min.js",
		"offlineClient.js",
		"images/redlightgreenlighthowto-sheet0.png",
		"images/redlightgreenlighthowto-sheet1.png",
		"images/redlightgreenlighthowto-sheet2.png",
		"images/play-sheet0.png",
		"images/gun-sheet0.png",
		"images/bg-sheet0.png",
		"images/r2-sheet0.png",
		"images/r3-sheet0.png",
		"images/r1-sheet0.png",
		"images/l2-sheet0.png",
		"images/l1-sheet0.png",
		"images/ghost-sheet0.png",
		"images/ghost-sheet1.png",
		"images/l11-sheet0.png",
		"images/current.png",
		"images/l3-sheet0.png",
		"images/top-sheet0.png",
		"images/bottom-sheet0.png",
		"images/center-sheet0.png",
		"media/tap.m4a",
		"media/tap.ogg",
		"media/light beam.m4a",
		"media/light beam.ogg",
		"media/game over.m4a",
		"media/game over.ogg",
		"media/light beam end.m4a",
		"media/light beam end.ogg",
		"media/light beam mid.m4a",
		"media/light beam mid.ogg",
		"media/light beam start.m4a",
		"media/light beam start.ogg",
		"media/ghost sound.m4a",
		"media/ghost sound.ogg",
		"media/game over (1).m4a",
		"media/game over (1).ogg",
		"media/bg.m4a",
		"media/bg.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}